spring.application.name=ApiGateway
server.port=8080

# Config Server
spring.config.import=optional:configserver:http://localhost:8083

# Eureka
#eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# Redis (Rate Limiter)
#spring.redis.host=localhost
#spring.redis.port=6379

# Actuator
management.endpoints.web.exposure.include=*

# Gateway Routes
# spring.cloud.gateway.routes[0].id=product-service
##spring.cloud.gateway.routes[0].uri=lb://PRODUCT-SERVICE
#spring.cloud.gateway.routes[0].predicates[0]=Path=/products/**
#spring.cloud.gateway.routes[0].filters[0]=RequestRateLimiter
#
#spring.cloud.gateway.routes[1].id=order-service
#spring.cloud.gateway.routes[1].uri=lb://ORDER-SERVICE
#spring.cloud.gateway.routes[1].predicates[0]=Path=/orders/**
#spring.cloud.gateway.routes[1].filters[0]=RequestRateLimiter
#
## Rate Limiter Config
spring.cloud.gateway.redis-rate-limiter.replenishRate=5
spring.cloud.gateway.redis-rate-limiter.burstCapacity=10
#
## Circuit Breaker
# spring.cloud.gateway.routes[1].filters[1]=CircuitBreaker=name=orderCB,fallbackUri=forward:/fallback
#spring.cloud.gateway.routes[1].filters[1].name=CircuitBreaker
#spring.cloud.gateway.routes[1].filters[1].args.name=orderCB
#spring.cloud.gateway.routes[1].filters[1].args.fallbackUri=forward:/fallback